CREATE DATABASE Jogos;

USE Jogos;

CREATE TABLE Jogo(
   IdJogo VARCHAR(40) PRIMARY KEY,
   Imagem VARCHAR(100),
   Titulo VARCHAR(100) NOT NULL,
   IdGenero VARCHAR(40) FOREIGN KEY REFERENCES Genero(IdGenero)
);

CREATE TABLE Genero(
   IdGenero VARCHAR(40) PRIMARY KEY,
   Nome VARCHAR(100) NOT NULL
);

CREATE TABLE Usuario(
   IdUsuario VARCHAR(40) PRIMARY KEY,
   Nome VARCHAR(100) NOT NULL,
   Senha VARCHAR(60) NOT NULL,
   Email VARCHAR(100) NOT NULL UNIQUE
);

DROP TABLE Usuario;