CREATE DATABASE Jogos;

USE Jogos;

CREATE TABLE Jogo(
    IdJogo UNIQUEIDENTIFIER PRIMARY KEY,
    Imagem VARCHAR(100),
    Titulo VARCHAR(100) NOT NULL,

    IdGenero UNIQUEIDENTIFIER,

    CONSTRAINT FK_Jogo_Genero
        FOREIGN KEY (IdGenero)
        REFERENCES Genero(IdGenero)
);

CREATE TABLE Genero(
    IdGenero UNIQUEIDENTIFIER PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL
);

DROP TABLE Jogo;
DROP TABLE Genero;

CREATE TABLE Usuario(
   IdUsuario VARCHAR(40) PRIMARY KEY,
   Nome VARCHAR(100) NOT NULL,
   Senha VARCHAR(60) NOT NULL,
   Email VARCHAR(100) NOT NULL UNIQUE
);

DROP TABLE Usuario;